### ISSUE TITLE
FUSE 2.8.0 required?

### ISSUE THREAD

**Issue by alexreg** [jborg/attic#134]
Installing via pip3 on OS X tells me that FUSE 2.8.0 is required, and I only have 2.7.2 (OSXFUSE). The problem is, this is the latest release of OSXFUSE. Does this mean that there is no hope getting Attic to install on OS X then?

**Comment by dahjelle** [comment]
FWIW, I've successfully installed attic 0.14 yesterday on OS X with OSXFuse 2.7.4 installed via Homebrew. Perhaps things have changed since you last tried?

**Comment by alexreg** [comment]
Interesting. Did you just run `sudo pip3 install Attic`?

**Comment by dahjelle** [comment]
Looks like I first did a `brew install python3` (which installed Python 3.4) and then did a `pip3.4 install attic`. But, essentially, yes.

Hmm…now that I think about it, I think I actually **didn't** have OSXFuse installed until **after** I installed attic? Maybe that's the trick?

**Comment by alexreg** [comment]
Hmm, now I get a weird different error:

```
cythoning attic/platform_darwin.pyx to attic/platform_darwin.c

error: [Errno 2] No such file or directory: '/private/tmp/pip_build_root/attic/attic/platform_darwin.pyx'
```

**Comment by dahjelle** [comment]
Hrm. I'm afraid I'm not any more help, unless there are other details of my config that you think would be useful: I'm pretty much a complete Python n00b. I'm guessing that's not a `brew`'d Python, though? Maybe worth trying homebrew and see if that helps?

**Comment by alexreg** [comment]
Nope, it's most definitely a Homebrew version of Python!

Anyway, thanks for your suggestions. Maybe the developer @jborg can step in at some point and advise...

Here's my full pip.log in case it can help anyone diagnose the issue... https://gist.github.com/2b3c02f73d071d9b0c9b

**Comment by TheSquimmy** [comment]
Am I correct in saying that mounting on OS X is currently impossible?

Attic requires llfuse which in turn requires Fuse 2.8 - a version of which is not available on OS X. So the feature doesn't work on OS X?

**Comment by ThomasWaldmann** [comment]
@TheSquimmy see there, that was after 0.14: https://github.com/jborg/attic/commit/df6324b725ff8cb68b12fee8af0c1ca7e38592af

**Comment by TheSquimmy** [comment]
I'm sorry, I don't quite understand what i'm looking at with that commit. I can install Attic fine - I just can't use the mount function due to the reliance on a not-yet-released version of osxfuse. Does that commit relate to that?

**Comment by alexreg** [comment]
Installing the latest version from source works for me on OS X 10.10.2. (I just ran `python3 setup.py install` as I presume I should).

**Comment by TheSquimmy** [comment]
And then mounting the repository works as well?

**Comment by ThomasWaldmann** [comment]
The commit means that attic/*.pyx files were missing in 0.14. If you look at the logs posted above, you see that cython complains about them being not found.

While you do not have them in the pypi attic 0.14 package (pip install attic), you can use the github repo based installation described in the docs. You'ld need C compiler and Cython then to compile pyx to c and c to binary.

**Comment by alexreg** [comment]
@TheSquimmy Ah no, I forgot to try that. I still get the error `attic: the "llfuse" module is required to use this feature`. Is this what you get too?

@ThomasWaldmann Where are these instructions to build the pyx files? They're not in the README file for sure.

**Comment by ThomasWaldmann** [comment]
You don't "build" the .pyx files, they are (Cython) source code written by @jborg and they get compiled to .c and then to binary. They contain some lowlevel stuff for platform support (of Linux, of OS X, etc.).

**Comment by alexreg** [comment]
This is how my install goes: https://gist.github.com/a08594a07478edf55abe – seems to be all fine.

However, I still get the above error about llfuse. My `PYTHONPATH` is `:/usr/local/Homebrew/lib/python3.4/site-packages`, and this contains both `llfuse/` and `llfuse-0.40-py3.4.egg-info/`, but Attic seems unable to find this. What's up here?

**Comment by ThomasWaldmann** [comment]
BTW, try to install llfuse package - you seem to miss it. Either pip install llfuse or use a package for your OS.

**Comment by ThomasWaldmann** [comment]
btw, if you have IRC: #attic on chat.freenode.net :)

**Comment by ThomasWaldmann** [comment]
@alexreg install log looks good. No idea why it doesn't find llfuse then.

You could try to directly start the python interpreter:

$ python3.4
>>> import llfuse

(post what it outputs here, if there is an error msg)

**Comment by ThomasWaldmann** [comment]
Yes, 2.8.0 is required and osxfuse is still < 2.8.0, see there:

https://github.com/osxfuse/osxfuse/issues/200

**Comment by ThomasWaldmann** [comment]
The github master branch of osxfuse has version 3.0.1 - maybe some Mac OS X user could test whether llfuse (attic mount) works now on OS X using that code.

**Comment by alexreg** [comment]
Installed latest osxfuse master branch; seemed to go gine. I can run the python3 shell and successfully import *llfuse* too, which is good. However, using `attic mount`, I still get the following:

```sh
Mounting filesystem
the OSXFUSE file system is not available (19)
attic: Exiting with failure status due to previous errors
```

**Comment by alexreg** [comment]
Okay, I just installed the version 3.0.3 released over on osxfuse (which seems to be even ahead of the master branch!) and things seem to work nicely. Only thing I would suggest now is that for `attic mount` when running in foreground mode, Ctrl+D (EOF), and Ctrl+C (SIGINT) should do something, rather than just being ignored.

**Comment by ThomasWaldmann** [comment]
https://github.com/osxfuse/osxfuse/releases < here is 3.0.3 prerelease.

**Comment by alexreg** [comment]
Is this release ahead of the master branch even? But anyway, works sufficiently for Attic. :)

**Comment by ThomasWaldmann** [comment]
I've no idea, just wanted to give the link as the download is not yet in the main dl area (due to prerelease, likely).

**Comment by alexreg** [comment]
Yeah. Oh well, at least it means Attic works on Mac right now! Thanks for helping resolve this.

Did you note my suggestions for foreground mode of `attic mount`, incidentally?

**Comment by ThomasWaldmann** [comment]
@alexreg I am not sure Ctrl-C should do something there as you first need to unmount before the FUSE "serving part" may terminate.

Can you test (on OS X) what happens when you unmount the FUSE file system (on linux, that is fusermount -u mountpoint)? Does the foreground "attic mount" terminate automatically after that?

**Comment by alexreg** [comment]
Yes, it does. But couldn’t Ctrl+C be caught and the unmount done there? That would be quite convenient.

**Comment by ThomasWaldmann** [comment]
Ctrl-C works for me. But it is only processed when a fuse filesystem access triggers the code. I checked the code and if the fuse main is left (e.g. by ctrl-c), it calls close to unmount. So nothing to do there I guess.

**Comment by alexreg** [comment]
Ah. You can’t have it listen outside of triggers by the FUSE filesystem? Because if anything, that’s the worst time to unmount…

**Comment by ThomasWaldmann** [comment]
@alexreg oh, missed to reply...

yes, i think the fuse code only gets active when called. but I am no way a FUSE expert.

but I think this issue can be closed now as there is a new FUSE for OS X and you tested that it works (== works as usual).

**Comment by alexreg** [comment]
right!

**Comment by ThomasWaldmann** [comment]
@alexreg ok, then close it please (I can't).

**Comment by alexreg** [comment]
I thought you were an admin here? AnywY, it's done.

**Comment by STRML** [comment]
For the record, if anyone else comes across this, the 2.8.(0,1) versions of OSXFUSE did not allow me to install `llfuse`, but the pre-release 3.x versions at https://github.com/osxfuse/osxfuse/releases did.

**Comment by alexreg** [comment]
Yes, I think this is already detailed above (and in the thread on the osxfuse project), but it doesn’t hurt to restate the solution clearly. :)

**Comment by steveschow** [comment]
did you guys ever figure out how to get attic mount working on osx?  I have just installed attic and llfuse, but the mount isn't working.  When I run the  mount command I get no errors, but when I try to ls the mount I get the following error:

`ls: mymount: Device not configured`

These are the steps I used to get attic installed, which seems to work fine for creating backups, but I just can't seem to mount them on osx:

1 - brew install python3
2 - pip install attic
2 - Install osxfuse 3.2.0 ( http://osxfuse.github.io )
3 - pip install llfuse

**Comment by ThomasWaldmann** [comment]
if it is a recent llfuse version: there have been incompatible changes. try with an older (< 1.0) llfuse.

**Comment by steveschow** [comment]
I tried both 2.8.3 and 3.2.0 of osxfuse, neither worked.

I have since tried the borg fork with osxfuse 3.2.0 and it works perfectly so I'm running with that for now.  thanks

**Comment by ThomasWaldmann** [comment]
I mean the llfuse package you installed with pip.

**Comment by steveschow** [comment]
if I get around to it I will try with older versions of llfuse to see it if works, but at this point I'm moving forward with borg which seems to be more up to date.  thanks

**Comment by fulldecent** [comment]
Right now I tried:
1.  `brew install python3`
2. `pip3 install attic`
3. Install osxfuse 2.8.3 ( http://osxfuse.github.io )
4. `pip3 install llfuse`

This still produces

> fuse version too old (found: b'2.7.3', required: 2.8.0)

**Comment by ThomasWaldmann** [comment]
the error msg / fuse versioning is confusing, it does not refer to the osxfuse version, but to the fuse api version (AFAIK).

Try some 3.x version from there: https://github.com/osxfuse/osxfuse/releases

**Comment by fulldecent** [comment]
Thank you this worked with Fuse 3.4.0!
