### ISSUE TITLE
Mounting a entire repo is not working

### ISSUE THREAD

**Issue by thiagoc** [jborg/attic#137]
```bash
$ sudo attic mount attic_repo test/

$ mount
atticfs on /home/innovare/test type fuse (ro,nosuid,nodev,relatime,user_id=0,group_id=0)

$ sudo ls test
20141124

$ sudo ls test/20141124
ls: cannot open directory test/20141124: Input/output error
```
The mountpoint is unmounted after this command. Mount a single archive works as expected.

**Comment by bram85** [comment]
See also issue #200. Seems to be related to the usage of relative paths. `attic mount` works if you specify absolute paths.

**Comment by ThomasWaldmann** [comment]
duplicate of #200, please close #137.
