### ISSUE TITLE
Backup from FTP

### ISSUE THREAD

**Issue by szepeviktor** [jborg/attic#159]
Good morning!

Could you start me up where to begin with adding plain FTP protocol to Attic?
I see that you use `Popen` on the `ssh` binary.

I would backup *from* FTP to local disk.

**Comment by jborg** [comment]
> I would backup from FTP to local disk.
If so, isn't http://curlftpfs.sourceforge.net/ all you need?

**Comment by szepeviktor** [comment]
Thank you.
