### ISSUE TITLE
info command reports zero bytes for "All archives" if only one archive in repo

### ISSUE THREAD

**Issue by dnnr** [jborg/attic#183]
For some reason, running `attic info` on a repository that contains only a single archive reports zero bytes for the original and compressed size of all archives:
```
[...]
Number of files: 37000

                       Original size      Compressed size    Deduplicated size
This archive:                5.99 MB            293.65 kB            293.65 kB
All archives:                    0 B                  0 B            293.65 kB
```
I don't suppose that this is intentional for some reason, but in case it is, I'd suggest replacing the `0 B` with something like `n/a`.

**Comment by dnnr** [comment]
Upon further inspection, it seems that the info command has some factor off by one. Even if a another, identical archive is created, the "All archives" sizes do not show the correct size (which would be twice the original size). So unless "All archives" is meant to refer to "All _other_ archives", the bug doesn't only apply to single-archive repos.

**Comment by ThomasWaldmann** [comment]
See PR #287.
