### ISSUE TITLE
Document source of python 3.4 libraries bundled with releases

### ISSUE THREAD

**Issue by stepps** [jborg/attic#204]
As the title says, the source of all the python 3.4 libraries bundled with releases is unknown. 
It would also be good to have the actual makefile used for releases, so proper rpms can be made

**Comment by ThomasWaldmann** [comment]
@stepps it sounds like you are packaging for some specific linux distribution and you want to create everything from sources. Maybe if you use the procedure used when installing from github repo checkout (or the tarball with the pure sources), this is closer to what you want (as there is only source in there). I think most of these binary (*.so) files you see in the binary packages are not needed for a distribution package as they will be provided by external dependencies (like openssl, llfuse).

Aside from build dependencies (cython, headerfiles, ... - see docs), there is only python-msgpack as python dependency (available from pypi).

**Comment by ThomasWaldmann** [comment]
close?

**Comment by stepps** [comment]
Yes, thanks
