### ISSUE TITLE
attic stops backup with [Errno 28] No space left on device

### ISSUE THREAD

**Issue by lockheed** [jborg/attic#240]
Happened twice already on the same backup (resumed), and there is over 100GB still free on the target drive.

-------------------------------------------------------------------------------------------------------------------------------
...
/mnt/Disk_D/FTP/GSM/i9195/TW Impacted/Impacted_ROM_v1/system/app/GoogleTTS.apk
/mnt/Disk_D/FTP/GSM/i9195/TW Impacted/Impacted_ROM_v1/system/app/GroupPlay_20.apk
attic: /mnt/Disk_D/FTP/GSM/i9195/TW Impacted/Impacted_ROM_v1/system/app/GroupPlay_20.apk: [Errno 28] No space left on device
/mnt/Disk_D/FTP/GSM/i9195/TW Impacted/Impacted_ROM_v1/system/app/Hangouts.apk
attic: Error: Archive panzor-2015-03-18T11:06:04.616478.checkpoint already exists
Command '('attic', 'create', '--exclude-from', '/etc/atticmatic/excludes.data', '/mnt/usb/data.attic::panzor-2015-03-18T11:06:04.616478', '/home/juha', '/mnt/Disk_D/#_Books'... , '--verbose', '--stats')' returned non-zero exit status 1
-------------------------------------------------------------------------------------------------------------------------------

The size of folders being backed up is ~130GB. The target drive is an empty BTRFS 250 GB hdd.

**Comment by ThomasWaldmann** [comment]
could it be that the source filesystem (or home dir there) was full? attic does some caching and that also needs space.

**Comment by lockheed** [comment]
Hmm, perhaps keeping the entire ~/.cache folder in ram is not the best idea. I will disable and and come back if the problem persists.

**Comment by ThomasWaldmann** [comment]
in the experimental branches of the https://github.com/attic/merge repo, you can disable the files cache, which reduces RAM usage significantly.

BUT: "no space left on device" does not sound like a RAM, but rather disk-full problem.

**Comment by lockheed** [comment]
I think disk=ram because I am using this https://wiki.archlinux.org/index.php/Anything-sync-daemon

**Comment by ThomasWaldmann** [comment]
That stuff is likely doubling the already-high RAM usage of attic, maybe rather don't do that.
But I don't think this doubling is an attic issue, so this ticket should be closed.

We already have other tickets about lowering RAM usage by switching off files and chunks cache.

**Comment by lockheed** [comment]
Couldn't agree more. Thanks for the tip.
