### ISSUE TITLE
Support for immutable old segments

### ISSUE THREAD

**Issue by chneukirchen** [jborg/attic#248]
It would be nice if attic supported a mode where taking a new backup does not modify existing segments.  Currently, segments are filled up to a certain size, so the last segment will likely be rewritten.

This feature would have several benefits:
- old segments can be marked read-only/immutable in the file system, to ensure consistency
- replication is made easier, since there is only one version of each segment file
- it is cheaper to store on backup cloud services such as Google Nearline or Amazon Glacier, where rewrites of recent data have additional cost (retrieval + removal cost).

(I think this should be fairly easy to implement by forcing a new segment at the beginning of a new archive, but I'm not yet familiar enough with the code to patch it.)

**Comment by jborg** [comment]
This is simply incorrect. Segment files are never modified once written, so there is only one "version" of each segment file. If some of the objects contained in a segment are deleted the remaining objects are relocated to a new segment file and the original segment file is deleted.

**Comment by chneukirchen** [comment]
Oh, you are right. I just checked it again and the behavior is a bit different than I remembered: When an incomplete segment is filled up, its actually renamed:

```
initial
db173be241c0a47dfc8d2d8afae4d02b  test.attic/README
eb6146b76ac37af7a3867f09a0230bba  test.attic/config
10aa77b82e8ea2f5a2a921e843238bfa  test.attic/data/0/0
49c8bf12d9951ef468b00f636a0fa401  test.attic/hints.0
6dc9b50a652b5bd60f1478c9cf1c77e4  test.attic/index.0

first backup
db173be241c0a47dfc8d2d8afae4d02b  test.attic/README
eb6146b76ac37af7a3867f09a0230bba  test.attic/config
b361d84aae38caf4da7e37218468d47f  test.attic/data/0/1
f11057b67e65f6ac5f61c8c66fc3231d  test.attic/data/0/3
ffac940fef6e85c39ee8ed06979d9b75  test.attic/hints.3
0aab634a1c8825dca4351077245c7d52  test.attic/index.3

second backup
db173be241c0a47dfc8d2d8afae4d02b  test.attic/README
eb6146b76ac37af7a3867f09a0230bba  test.attic/config
b361d84aae38caf4da7e37218468d47f  test.attic/data/0/1
748335d12e4ac1e41c481096ae681c5e  test.attic/data/0/5
0607ecb5f033e5573ecaad1056a3ad05  test.attic/data/0/6
623feb70c147a10c9612d2505870b812  test.attic/hints.6
3ec391f5bc429bd61e59da222481f503  test.attic/index.6
```

Still, the 0/3 segment has been removed (it probably ended up in 0/5).
IMO it would be nicer to keep the 0/3 as is and start with a fresh segment every time.

(Of course when you want to delete data you have to touch segments, but I'm talking about adding new backups only.)
