### ISSUE TITLE
improve restores by posix_fallocate

### ISSUE THREAD

**Issue by ThomasWaldmann** [jborg/attic#260]
on POSIX systems, one can tell the filesystem how much data one intends to write into a new file, so it can optimize disk space allocation (and maybe avoid fragmentation when other space allocation on the filesystem happens in parallel).

it's not a very critical thing to have, but if we can simply add it, why not...

see also #252 about posix_fadvise, which is somehow related.

**Comment by ThomasWaldmann** [comment]
Note: I tried using posix_fallocate for the repo segment writes done by "attic create", but somehow it triggered malfunctions. I guess it is somehow caused by the file append mode and that the file then looks like it is the allocated size big even if you did not yet write any data into it. I tried to solve with seek, but it did not work.

I think it is still worth trying for "attic extract" and files not using append mode.

**Comment by enkore** [comment]
See https://github.com/borgbackup/borg/issues/5#issuecomment-229792783

> > I'd tick "improve restores by posix_fallocate" because it has next to none positive impact on traditional FSes and (reportedly) negative impact on CoW FSes like ZFS and btrfs
> 
> Another very bad thing (tm) about fallocate is that if the FS doesn't support it glibc implements the _worst-possible fallback ever._

(both m, cross-media quoting so to speak)
