### ISSUE TITLE
Write-only serve mode

### ISSUE THREAD

**Issue by fl0at** [jborg/attic#278]
If a server using attic for backups gets compromised, the malicious actor can (as far as I can tell) delete the *entire* backup history on the remote server with ease.

Would it be difficult to implement a "write-only" mode for the remote serve command, so that the bad actor can't prune or delete backups? (Ideally, a create-only mode would be preferred, so they can't even extract/mount past backups)

(Obviously, sensible ssh settings set by the user are needed here too, or their work can still be undone)

**Comment by dnnr** [comment]
There is already an open ticket on that topic: #162 

And as far as I could tell, it is actually a bit complicated, so I don't expect this to happen any time soon.

**Comment by fl0at** [comment]
Ah, darn! Sorry about that. :)
