### ISSUE TITLE
Archive should be marked as "uncomplete" when attic create didn't finish

### ISSUE THREAD

**Issue by varac** [jborg/attic#280]
when i create a new archive, and cancel is in between, attic list shows this archive like all other (complete) archives. 
It should better indicate uncomplete archives (maybe by adding a "uncomplete" tag behind the archive name).

**Comment by jborg** [comment]
Really? Aborted "attic create" should not result in an archive with the requested name. 

But if the create operation was running for more than 5 minutes you should see a checkpoint archive named "<yourarchivename>.checkpoint". Is that what you're seeing?

**Comment by varac** [comment]
hugh, i failed to reproduce - maybe i was confused. closing until i reencounter it again.

**Comment by jdchristensen** [comment]
Similar behaviour was also reported on the mailing list:

http://librelist.com/browser//attic/2015/3/30/how-do-i-resume-a-backup/

I couldn't reproduce it, but Jean Jordaan says it happens to him.
