### ISSUE TITLE
Installation instructions on webpage misleading and dangerous

### ISSUE THREAD

**Issue by danmbox** [jborg/attic#293]
The current installation instructions on https://attic-backup.org/ are misleading, because `pip install attic` will fail ("requires Python 3.2 or later" on both Ubuntu 14.04 and the latest 15.04) and dangerous (apt-get install attic currently installs a data-corruption prone msgpack 0.4.2 on Ubuntu Vivid).

Please add correct instructions. I would suggest using virtualenv to minimize impact on the system:

> apt-get install python3-dev libacl1-dev libssl-dev
> virtualenv -p python3 attic; cd attic
> ./bin/pip3 install attic

**Comment by ThomasWaldmann** [comment]
@danmbox this is the wrong place to bring up distribution issues (like distribution x packaging a buggy version of some attic dependecy) - this should be (urgently) brought to the attention of that package's maintainer in distribution x. They need to upgrade to >=0.4.6 asap.

Also, setup.py of attic should require >= 0.4.6 ofc.

About pip vs. pip3: yes, I have also seen that. But if you created a virtualenv with python3, you can also invoke pip from the virtualenv (will be same as pip3). So it seems to only matter if you work in a namespace where pip exists for both python 2 and 3.

**Comment by danmbox** [comment]
This is a bug report against the attic webpage, https://attic-backup.org/ (do you recommend a different issue tracker for that)? A backup system is a special kind of software, people rely on it etc, so you should provide safe installation instructions and avoid ones that could lead to heartbreak and sorrow.

Unless you create the virtualenv with `-p python3`, it's a python2 env, into which attic subsequently refuses to install. Once you get a py3 env, yes, it seems bin/pip is identical to bin/pip3.

Having python, pip etc mean different things on different platforms strikes me as a particularly nasty portability issue. That is why distros use python/python3, pip/pip3. And it's not like attic can install under python2.

I have already created bug reports on Launchpad for Ubuntu -- we've talked about that already

**Comment by danmbox** [comment]
And let's not be idealistic, Ubuntu will probably stick with a broken msgpack for a long time (partly because it doesn't have that many attic and saltstack users to ask them to upgrade). Furthermore, at some point in the future there could be ANOTHER msgpack data corruption bug (they have a good track record in that respect), or attic could start depending on another library with version issues.

In a virtualenv you can ask users to install specific versions of the package, or refuse to install if the system-wide version is broken.

**Comment by ThomasWaldmann** [comment]
I agree it might be confusing or maybe frustrating with pip/pip3, python/python3, but the the python/pip version used by a distribution if you invoke "python" or "pip" depends on whatever they consider as their standard python version (similar for when you are inside a virtualenv). Currently this is often still python 2, but a few dists already switched to 3.

I agree that it is currently better to use a virtualenv to easily get the latest (and most bug free) stuff.
Or maybe alternatively the binary download?

**Comment by danmbox** [comment]
Sure, "naked pip" or "naked python" might mean version 3 for some smaller distributions (any major ones?) But using python3 / pip3 should be safe on any system (if not, please let me know where to file bugs -- I really don't want my python scripts to break in the future).

Are we looking to save the user typing some characters? Because most users prefer copy/paste-able instructions.

**Comment by jdchristensen** [comment]
I agree that the webpage should point out some of the current buggy things to avoid.
But is there any evidence that using a compiled msgpack 0.4.2 causes any problems with attic?
I've only heard of problems with the pure python fallback, and haven't heard of problems
with the standard Ubuntu package.

**Comment by danmbox** [comment]
@jdchristensen Well, there is evidence of actual data corruption using attic, e.g. https://github.com/jborg/attic/issues/264

So, @ThomasWaldmann was proposing that it might come from msgpack < 0.4.6 (see other referenced issues in that discussion). But the truth is we don't know -- perhaps it's not msgpack, but attic itself.

**Comment by jborg** [comment]
Yeah, I guess explicitly referring to pip3 instead of just pip doesn't hurt so I've pushed a fix, and also added a short thing about virtualenv.

I'm no ubuntu user myself but if you believe that they ship a broken version of msgpack, please let them know. They are known to backport bugfixes if needed.

**Comment by danmbox** [comment]
Great thanks.

As I've mentioned several times, I've opened a msgpack bug report with Ubuntu the first time I learned about the problem (https://bugs.launchpad.net/ubuntu/+source/msgpack-python/+bug/1443213). But unless several people confirm that report, it will just get ignored. I'm guessing there aren't a whole lot of Ubuntu attic and saltstack users

**Comment by jdchristensen** [comment]
That launchpad bug mentions msgpack bug 124, but that bug only affects the pure python version of msgpack, so isn't relevant to the Ubuntu package.  I don't know how relevant bug 114 is, but I haven't
heard of problems using compiled msgpack 0.4.2 with attic.  In any case, you should edit your Ubuntu bug report to not mention bug 124.

**Comment by danmbox** [comment]
So they can not fix it with more certainty, yes.

I've added mentions to other issues from https://github.com/msgpack/msgpack-python/issues/139 and the fact that #124 only affects the pure py version. Though that report is not about attic in particular.
