### ISSUE TITLE
Add disk space preview command

### ISSUE THREAD

**Issue by mbrodala** [jborg/attic#296]
It would be nice if there was a command or something similar to calculate how much disk space can be saved by using attic without actually doing a backup. This way one can more easily decide which backup option to use or try different scenarios.

**Comment by ThomasWaldmann** [comment]
Would you still think it is helpful even if it took almost as long as a real backup?

It would have to read all files completely, chunk them, compress them - just not encrypt and not save them.

**Comment by mbrodala** [comment]
"Compress" does mean the deduplication by chunk here?

Thinking about this once more unless the whole source directory is read into memory, Attic will most likely not be able to properly deduplicate data without actually storing it.

So would something like this be possible at all?

**Comment by dragetd** [comment]
You cannot tell how well data will compress or deduplicate without reading all of it. Even rough estimates (by only reading few files) could be very wrong.

But you could go through the whole backup process without storing the data. borg has --dry-run feature for that.

**Comment by ThomasWaldmann** [comment]
create --dry-run is mostly helpful for tuning the excludes, but as it does not read the file contents (nor try to compress or dedup them), it doesn't help here.

so, i don't think this solvable in a way that is much faster than actually doing a backup.

**Comment by mbrodala** [comment]
Thanks for the evaluation.
