### ISSUE TITLE
Question: list files modified/added in archive

### ISSUE THREAD

**Issue by saptarshiguha** [jborg/attic#301]
Hello,

Lovely software.Thanks. 

Once I've added an archive

attic create --stats archivename

is there a way to show files added/modified (essentially a diff between this and the previous archive in time)

Cheers

**Comment by ThomasWaldmann** [comment]
alternatively, with a better create -v output, one could get that list from there also.

**Comment by ThomasWaldmann** [comment]
Duplicate of #158, please close.
