### ISSUE TITLE
New security code breaks access to repos (in general)

### ISSUE THREAD

**Issue by ThomasWaldmann** [jborg/attic#303]
If one loses the .cache directory on the backupped machine (or tries to add to same repo from different machine), one loses repo "create" access:

```
$ attic init repo.attic
$ attic create /mnt/usb/repo.attic::1 .
$ rm -rf ~/.cache/attic/*   # or just try from another machine
$ attic create /mnt/usb/repo.attic::2 .
Warning: Attempting to access a previously unknown unencrypted repository.
attic: error: Cache initialization aborted
```
That's all, it doesn't ask whether one wants to override that or not.

**Comment by bricewge** [comment]
Have a look at #299.
Setting `"ATTIC_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes"` and the running `attic create` manually solved this is for me.

**Comment by jborg** [comment]
Yeah, sorry about that. It looks like there was a typo in a last minute change I did that prevented the interactive prompt from working properly. I've fixed that now. I'll probably make a new release in the near future
