### ISSUE TITLE
Wrong example for prune command

### ISSUE THREAD

**Issue by petacz** [jborg/attic#306]
**--monthly=-1** option is probably missing **keep-**monthly prefix or this option it is not documented.
Also **-1** option is not documented. Probably means "infinite number of backups".
```
# Keep 7 end of day, 4 additional end of week archives,
# and an end of month archive for every month:
$ attic prune /data/myrepo --keep-daily=7 --keep-weekly=4 --monthly=-1

# Keep all backups in the last 10 days, 4 additional end of week archives,
# and an end of month archive for every month:
$ attic prune /data/myrepo --keep-within=10d --keep-weekly=4 --monthly=-1
```

**Comment by ThomasWaldmann** [comment]
--monthly was the old way to specify (and is deprecated), --keep-monthly is the new way. so yes, this is a small doc bug.

-1 is documented:
"Specifying a negative number of archives to keep means that there is no limit."

**Comment by petacz** [comment]
I overlooked the info about negative number. I was looking for a value -1 :)

Thanks

**Comment by ThomasWaldmann** [comment]
@petacz maybe reopen until the wrong example is fixed.

There is https://github.com/jborg/attic/pull/308 but until it is merged into master (or fixed in other ways), it is not fixed.
