### ISSUE TITLE
Prune Question

### ISSUE THREAD

**Issue by whiteadam** [jborg/attic#310]
Apologies in advance if this is a silly question or has been answered before. I might also be doing this wrong.

I am currently backing up about 12 servers to a single remote repo with the archives being $HOSTNAME-DATE. When I ran prune, I expected it to keep the last 7 of EACH archive, but instead it only kept 7 archives period, by date. Is this normal?

Backup command:
```
attic create $REPOSITORY::$HOSTNAME-`date +%Y-%m-%d` / --exclude /proc --exclude /sys
```

Prune command:
```
attic prune -v $REPOSITORY --keep-daily=7 --keep-weekly=4 --keep-monthly=3
```

Am I doing it wrong? It feels like I'm doing it wrong.

**Comment by jborg** [comment]
To Attic a repository is just a bunch of archives with user assigned names. You need to tell prune that you only want to operate on a subset of the archives. Something like this:

```sh
attic prune -v $REPOSITORY --keep-daily=7 --keep-weekly=4 --keep-monthly=3 --prefix $HOSTNAME
```

**Comment by whiteadam** [comment]
Thanks @jborg I was actually just reading #10 

I think your strategy may be better. I was trying to run the prune command on the attic server only, but may need to run it on the clients instead with $HOSTNAME.
