### ISSUE TITLE
attic --help serve ?

### ISSUE THREAD

**Issue by centminmod** [jborg/attic#343]
attic --help shows

```
Available commands:
  {serve,init,check,change-passphrase,create,extract,delete,list,mount,info,prune,help}
```

but what is serve command ? it's not outlined at https://attic-backup.org/usage.html ?

**Comment by ThomasWaldmann** [comment]
You don't need to use serve manually, it is used internally when invoking a remote attic via ssh.

**Comment by centminmod** [comment]
ok i see thanks @ThomasWaldmann

**Comment by ThomasWaldmann** [comment]
please close.
