### ISSUE TITLE
extract path issue?

### ISSUE THREAD

**Issue by pamamolf** [jborg/attic#348]
Hi

I just try to backup my public folder /home/nginx/domains/mydomain.com/public using the command:

attic create /backup/backupattic.attic::mydomain4 /home/nginx/domains/mydomain.com/public/

As i can see all are ok:

attic list /backup/backupattic.attic::mydomain4
drwxr-x--- nginx  nginx         0 Sep 04 11:35 home/nginx/domains/mydomain.com/public
-rw-r--r-- nginx  nginx        54 Sep 02 18:02 home/nginx/domains/mydomain.com/public/3B6B8C0D442FE59E2901F666B21E3FF7.txt
-rw-r----- nginx  nginx        74 Aug 28 13:19 home/nginx/domains/mydomain.com/public/index.html

then i delete the file 3B6B8C0D442FE59E2901F666B21E3FF7.txt and i try to restore using:

attic extract -v /backup/backupattic.attic::mydomain4
drwxr-x--- nginx  nginx  0 Sep 02 18:03 home/nginx/domains/mydomain.com/public
-rw-r--r-- nginx  nginx  54 Sep 02 18:02 home/nginx/domains/mydomain.com/public/3B6B8C0D442FE59E2901F666B21E3FF7.txt
-rw-r----- nginx  nginx  74 Aug 28 13:19 home/nginx/domains/mydomain.com/public/index.html

And when i try to check for the backup if it i sok i notice that the extraction was done inside the home/nginx/domains/mydomain.com/ like:

home/nginx/domains/mydomain.com/home/nginx/domains/mydomain.com/public

Any ideas?

Thanks

**Comment by ThomasWaldmann** [comment]
attic restores the full path starting from the current directory.

**Comment by pamamolf** [comment]
Full path is:

/home/nginx/domains/mydomain.com/public

and i confirm it by checking the backup file:

attic list /backup/backupattic.attic::mydomain4
drwxr-x--- nginx nginx 0 Sep 04 11:35 home/nginx/domains/mydomain.com/public
-rw-r--r-- nginx nginx 54 Sep 02 18:02 home/nginx/domains/mydomain.com/public/3B6B8C0D442FE59E2901F666B21E3FF7.txt
-rw-r----- nginx nginx 74 Aug 28 13:19 home/nginx/domains/mydomain.com/public/index.html

Everything is fine...

But when i restroe i don't get for example the file index.html here as it should be:

home/nginx/domains/mydomain.com/public/index.html

but i get it here:

home/nginx/domains/mydomain.com/home/nginx/domains/mydomain.com/public/index.html

**Comment by pamamolf** [comment]
Ok now i try to create a backup without the ending slash like this:

attic create /backup/backupattic.attic::mydomain4 /home/nginx/domains/mydomain.com/public

I can view all files with correct paths when i mount the backup and before i extract the files i delete the index.html from here:

/home/nginx/domains/mydomain.com/public/index.html

Then i try to restore using :+1: 

attic extract -v /backup/backupattic.attic::mydomain
home/nginx/domains/mydomain.com/public
home/nginx/domains/mydomain.com/public/index.html

And look ok but when i check if the file index.html restore the file is  not there:
home/nginx/domains/mydomain.com/public/

But i notice that now i do not have the problem with the extraction here:
home/nginx/domains/mydomain.com/home/nginx/domains/mydomain.com/public/index.html

**Comment by ThomasWaldmann** [comment]
"current directory" means where you currently are when you invoke attic from the shell (see output of "cwd"). pathes are constructed relative to there.

so if you have the full pathes starting from the root directory in the archive and you want to extract it to the original place, "cd /" before invoking attic.

**Comment by pamamolf** [comment]
I am running all comands from root ~

[root@server ~]#

**Comment by pamamolf** [comment]
Can i have please a sample command to use for backup and extract for backing up this folder?

home/nginx/domains/mydomain.com/public

Thank you

**Comment by ThomasWaldmann** [comment]
try to reproduce your issue with something like this:

```
attic init repo
attic create repo::archive /a/b/c
attic extract repo::archive a/b/c
```

If you can make a script (like above) that reproduces / shows your issue, maybe delete all your above posts and just show the issue with your script and its output. That will be much clearer, easier to read and easier to reproduce.

Your script could then be used to make a (failing) test case and that could be the basis of getting it fixed (and making sure it never comes back).

**Comment by pamamolf** [comment]
I just try running the commands as root and here is the outpout:

[root@server ~]# ls /home/nginx/domains/mydomain.com/public/
index.html  New folder

You can see that i have there a file index.html

[root@server ~]# attic create /backup/backupattic.attic::mydomain9 /home/nginx/domains/mydomain.com/public

At this point i delete manually the index.html file

[root@server ~]# attic extract /backup/backupattic.attic::mydomain9 home/nginx/domains/mydomain.com/public
[root@server ~]# ls /home/nginx/domains/mydomain.com/public/
New folder

There is no index.html file after extraction of the backup :(

**Comment by jdchristensen** [comment]
As was explained, the extraction is done relative to the current directory.

So do "cd /" before running the extract command, and all should be well.

**Comment by pamamolf** [comment]
Sorry for my bad english :(

Yes that did the trick :)

[root@server ~]# cd /
[root@server /]# attic extract /backup/backupattic.attic::mydomain9
[root@server /]# ls /home/nginx/domains/mydomain.com.com/public/
index.html  New folder

I got the index.html back :)

As i am not expert how can i do it to avoid the cd / command?

Is there any way?

Thank you

**Comment by ThomasWaldmann** [comment]
@pamamolf not, it always works relative to the current directory. IIRC there is a ticket about adding a target dir option.

**Comment by pamamolf** [comment]
Adding a target dir option will be great :)

Thanks all of you :)

**Comment by pamamolf** [comment]
One last problem:

[root@server ~]# fusermount -u /backup/restore-mount
-bash: fusermount: command not found

**Comment by ThomasWaldmann** [comment]
@pamamolf close this issue if it is solved. and don't mixup issues.
