### ISSUE TITLE
attic init force remote path

### ISSUE THREAD

**Issue by eack** [jborg/attic#363]
Hello,

is it possible to force a remote path for a repository:
for example: `attic init user@hostname:repository.attic:/home/user/my-repo.attic`

**Comment by ThomasWaldmann** [comment]
```
attic init user@hostname:/full/path/to/repo.attic
```

Is it that what you mean? (close if that solves your issue)

**Comment by eack** [comment]
Oh sorry,
now i recognize my wrong syntax.
Thanks, everything works!
