### ISSUE TITLE
attic check results in error "attic: Error: Inconsistency detected. Please run "attic check ...""

### ISSUE THREAD

**Issue by flicaflow** [jborg/attic#365]
I try to extract a backup, "attic list" took ages and finally exited with the error message:
  attic: Error: Inconsistency detected. Please run "attic check ..."
running "attic check ..." exits the archive consistency check with the same error message.
Also trying to execute check with --repair does not succeed.

I'm running attic 0.13 on a fresh Ubuntu 15.10.

Any idea how I get my data back?

**Comment by ThomasWaldmann** [comment]
come to freenode irc #attic maybe we can find a solution. create a copy of your backup repo for experiments.

**Comment by flicaflow** [comment]
Thanks for the help!
It turned out for some reason the manifest got lost. Updating to 0.16 and running attic check --repair fixed the problem.
