### ISSUE TITLE
Backup repository in amazon cloud drive using acd_cli

### ISSUE THREAD

**Issue by agrlh** [jborg/attic#376]
Hi,

I am using [acd_cli](https://github.com/yadayada/acd_cli) to mount my Amazon Cloud Drive on my server.
I would like to use it as a backup repository with attic. However, after issuing the init command attic ends up with the following error `attic: Error: /mnt/ACD/Backup/test is not a valid repository`

Here is what I did and what is written into the repository:

```
~ ❯❯❯ attic init -v /mnt/ACD/Backup/test
Initializing repository at "/mnt/ACD/Backup/test"
attic: Error: /mnt/ACD/Backup/test is not a valid repository
~ ❯❯❯ ll /mnt/ACD/Backup/test                                                         ⏎
total 0
drwxrwxrw- 1 alex alex   0 Feb  4 08:07 .
drwxrwxrw- 1 alex alex   0 Feb  4 08:06 ..
drwxrwxrw- 1 alex alex   0 Feb  4 08:07 data
-rwxrwxrw- 1 alex alex 148 Feb  4 08:07 config
-rwxrwxrw- 1 alex alex  28 Feb  4 08:07 README
~ ❯❯❯
```

If I then try to create a backup there, the following output is given

```
~ ❯❯❯ sudo attic create /mnt/ACD/Backup/test::init /var/www
attic: Error: Object with key b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not found in repository /mnt/ACD/Backup/test
```

Did anyone try a similar setup? Could this error be FUSE related?

Thanks!

**Comment by ThomasWaldmann** [comment]
I'ld guess the amazon cloud drive file system you use is not working good enough as a filesystem.
I guess even if it would work for the relatively "normal" fs operations, I'ld bet it would fail when it comes to posix locking (which is problematic enough, even on more "normal" filesystems).

**Comment by agrlh** [comment]
I see. Thanks!

**Comment by shezi** [comment]
That's not really helpful, though. What would need to be done to make an Amazon Drive a valid backup location?
