### ISSUE TITLE
Cannot extract to specific folder

### ISSUE THREAD

**Issue by misterch0c** [jborg/attic#377]
I created a backup like this:

`attic create backup.attic::my-backup /home/unkn0wn/stufftobackup`

And I want to restore it in another folder like:

`attic extract backup.attic::my-backup /home/unkn0wn/somefolder`

When I run this I get asked for my passphrase and then the program returns. If I run the same command without /home/unkn0wn/somefolder then the file gets extracted in the original folder... Am I doing something wrong?
I'm on Archlinux and got the package from the AUR

**Comment by ThomasWaldmann** [comment]
That's not how it works, it is `attic extract repo::archive [path_of_something_in_the_archive]`.

You can not give a target folder, but you can cd into any folder you like before calling attic.

You may want to combine this with `--strip-components`.

See `attic extract --help`.

If you only need a few files/directories, you could also use `attic mount` and a file manager for simplicity.

**Comment by misterch0c** [comment]
I see, I didn't understand it that way, thank you.
