### ISSUE TITLE
[EXPIRED] Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [jborg/attic#392]
Dear Jonas,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Python?
I’m told that [py2exe][1] might help you to achieve that.

[1]: http://py2exe.org/

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by ThomasWaldmann** [comment]
@sergeevabc attic development is rather inactive currently.

Maybe have a look at borgbackup (which is a fork of attic) - a contributor of it is building EXEs with cygwin included, see github issues.
