### ISSUE TITLE
pip install fails on ubuntu 18.04

### ISSUE THREAD

**Issue by TejasAvinashShetty** [jborg/attic#400]
(html2pdf) tejas@g3:~$ pip install Attic
Collecting Attic
  Downloading https://files.pythonhosted.org/packages/b5/a1/84a448f4c375a9c18d24626e212e289140083fd2ce3c6b4665cd139d92ba/Attic-0.16.tar.gz (232kB)
     |████████████████████████████████| 235kB 7.3MB/s 
Collecting msgpack-python
  Downloading https://files.pythonhosted.org/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgpack-python-0.5.6.tar.gz (138kB)
     |████████████████████████████████| 143kB 11.0MB/s 
Building wheels for collected packages: Attic, msgpack-python
  Building wheel for Attic (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/tejas/anaconda3/envs/html2pdf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rno7f0t1/Attic/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rno7f0t1/Attic/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ubjb6iwh --python-tag cp37
       cwd: /tmp/pip-install-rno7f0t1/Attic/
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/attic
  copying attic/repository.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/remote.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/platform.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/_version.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/archive.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/__init__.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/fuse.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/key.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/cache.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/xattr.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/lrucache.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/archiver.py -> build/lib.linux-x86_64-3.7/attic
  copying attic/helpers.py -> build/lib.linux-x86_64-3.7/attic
  creating build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/repository.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/platform.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/archive.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/hashindex.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/__init__.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/mock.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/chunker.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/key.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/xattr.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/lrucache.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/archiver.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/run.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/helpers.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  copying attic/testsuite/crypto.py -> build/lib.linux-x86_64-3.7/attic/testsuite
  running build_ext
  skipping 'attic/crypto.c' Cython extension (up-to-date)
  skipping 'attic/chunker.c' Cython extension (up-to-date)
  skipping 'attic/hashindex.c' Cython extension (up-to-date)
  skipping 'attic/platform_linux.c' Cython extension (up-to-date)
  building 'attic.crypto' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/attic
  /home/tejas/anaconda3/envs/html2pdf/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/tejas/anaconda3/envs/html2pdf/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/tejas/anaconda3/envs/html2pdf/include -fPIC -I/usr/include -I/home/tejas/anaconda3/envs/html2pdf/include/python3.7m -c attic/crypto.c -o build/temp.linux-x86_64-3.7/attic/crypto.o
  In file included from /home/tejas/anaconda3/envs/html2pdf/include/python3.7m/Python.h:11:0,
                   from attic/crypto.c:16:
  /usr/include/limits.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   #include <bits/libc-header-start.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/home/tejas/anaconda3/envs/html2pdf/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for Attic
  Running setup.py clean for Attic
  Building wheel for msgpack-python (setup.py) ... done
  Created wheel for msgpack-python: filename=msgpack_python-0.5.6-cp37-cp37m-linux_x86_64.whl size=99115 sha256=87cc81f0e042bd87aa89363aa8cd077291839730bd258bb85f616152e1cb334f
  Stored in directory: /home/tejas/.cache/pip/wheels/d5/de/86/7fa56fda12511be47ea0808f3502bc879df4e63ab168ec0406
Successfully built msgpack-python
Failed to build Attic
Installing collected packages: msgpack-python, Attic
    Running setup.py install for Attic ... error
    ERROR: Command errored out with exit status 1:
     command: /home/tejas/anaconda3/envs/html2pdf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rno7f0t1/Attic/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rno7f0t1/Attic/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4258991t/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-rno7f0t1/Attic/
    Complete output (50 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/attic
    copying attic/repository.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/remote.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/platform.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/_version.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/archive.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/__init__.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/fuse.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/key.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/cache.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/xattr.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/lrucache.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/archiver.py -> build/lib.linux-x86_64-3.7/attic
    copying attic/helpers.py -> build/lib.linux-x86_64-3.7/attic
    creating build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/repository.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/platform.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/archive.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/hashindex.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/__init__.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/mock.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/chunker.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/key.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/xattr.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/lrucache.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/archiver.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/run.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/helpers.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    copying attic/testsuite/crypto.py -> build/lib.linux-x86_64-3.7/attic/testsuite
    running build_ext
    skipping 'attic/crypto.c' Cython extension (up-to-date)
    skipping 'attic/chunker.c' Cython extension (up-to-date)
    skipping 'attic/hashindex.c' Cython extension (up-to-date)
    skipping 'attic/platform_linux.c' Cython extension (up-to-date)
    building 'attic.crypto' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/attic
    /home/tejas/anaconda3/envs/html2pdf/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/tejas/anaconda3/envs/html2pdf/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/tejas/anaconda3/envs/html2pdf/include -fPIC -I/usr/include -I/home/tejas/anaconda3/envs/html2pdf/include/python3.7m -c attic/crypto.c -o build/temp.linux-x86_64-3.7/attic/crypto.o
    In file included from /home/tejas/anaconda3/envs/html2pdf/include/python3.7m/Python.h:11:0,
                     from attic/crypto.c:16:
    /usr/include/limits.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
     #include <bits/libc-header-start.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/home/tejas/anaconda3/envs/html2pdf/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/tejas/anaconda3/envs/html2pdf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rno7f0t1/Attic/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rno7f0t1/Attic/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4258991t/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by anhofmann** [comment]
Attic is no longer maintained. Rather use borg: https://borgbackup.readthedocs.io/en/stable/index.html

**Comment by TejasAvinashShetty** [comment]
ok
